services:
  - type: web
    name: pdf-compressor
    env: python
    buildCommand: |
      apt-get update && apt-get install -y ghostscript
      pip install -r requirements.txt
    startCommand: python app.py
    plan: free
